// <auto-generated />
namespace LabSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Survey_Sample_Role_Report_Order_Laboratory_Invoice_Employee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Survey_Sample_Role_Report_Order_Laboratory_Invoice_Employee));
        
        string IMigrationMetadata.Id
        {
            get { return "201812271534596_Survey_Sample_Role_Report_Order_Laboratory_Invoice_Employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
